name: Deploy Shoe Store API to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::679835925078:role/GitHubActions-ShoeStore-DeployRole
          aws-region: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python requirements for CDK
        run: pip install -r requirements.txt

      - name: Make build script executable
        run: chmod +x ./build.sh

      - name: Run build script to package Lambda functions
        run: ./build.sh

      - name: Deploy with CDK
        run: cdk deploy --require-approval never